const ROUTES = {
  loginLinkRequest: 'auth/links/request',
  loginLinkVerify: 'auth/links/verify',
  loginLinkSent: 'auth/links/sent',
  invitationUnauthenticatedManagement: 'invitations',
  configureMe: 'configure/me',
  createOrganization: 'organizations/create',
  acceptInvitations: 'invitations/pending',
  dashboard: 'dashboard',
  team: 'team',
  teamPage: 'team/:activeTab/:status',
  members: 'members',
  invitations: 'invitations',
  invitationsPage: 'invitations/:status',
  pending: 'pending',
  registered: 'registered',
  accepted: 'accepted',
  declined: 'declined',
  expired: 'expired',
  cancelled: 'cancelled',
  organizations: 'organizations',
  organization: 'organizations/:organizationId',
  subscriptions: 'subscriptions',
  subscriptionFunnels: 'subscription-funnels',
  subscriptionFunnel: 'subscription-funnels/:subscriptionFunnelId',
  subscriptionFunnelPaymentIntent: 'subscription-funnels/:subscriptionFunnelId/payment-intents/:subscriptionPaymentIntentId',
  users: 'users',
  userPage: 'users/:userId/:activeTab',
  profile: 'profile',
  notifications: 'notifications',
  settings: 'settings',
  settingsPage: 'settings/:activeTab',
  information: 'information',
  address: 'address',
  billing: 'billing',
  invoices: 'invoices',
  security: 'security',
  subscribe: 'subscribe',
  paymentIntents: 'payment-intents',
};

export default ROUTES;
