const TAXES = [
  {
    code: 'al_tin',
    countryCode: 'AL',
    countryName: 'Albania',
    taxName: 'Albania Tax Identification Number',
    taxNumberPlaceholder: 'J12345678N',
    percentage: undefined,
  },
  {
    code: 'ad_nrt',
    countryCode: 'AD',
    countryName: 'Andorra',
    taxName: 'Andorran NRT number',
    taxNumberPlaceholder: 'A-123456-Z',
    percentage: undefined,
  },
  {
    code: 'ao_tin',
    countryCode: 'AO',
    countryName: 'Angola',
    taxName: 'Angola Tax Identification Number',
    taxNumberPlaceholder: '5123456789',
    percentage: undefined,
  },
  {
    code: 'ar_cuit',
    countryCode: 'AR',
    countryName: 'Argentina',
    taxName: 'Argentinian tax ID number',
    taxNumberPlaceholder: '12-3456789-01',
    percentage: undefined,
  },
  {
    code: 'am_tin',
    countryCode: 'AM',
    countryName: 'Armenia',
    taxName: 'Armenia Tax Identification Number',
    taxNumberPlaceholder: '02538904',
    percentage: undefined,
  },
  {
    code: 'au_abn',
    countryCode: 'AU',
    countryName: 'Australia',
    taxName: 'Australian Business Number (AU ABN)',
    taxNumberPlaceholder: '12345678912',
    percentage: undefined,
  },
  {
    code: 'au_arn',
    countryCode: 'AU',
    countryName: 'Australia',
    taxName: 'Australian Taxation Office Reference Number',
    taxNumberPlaceholder: '123456789123',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'AT',
    countryName: 'Austria',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'ATU12345678',
    percentage: 20,
  },
  {
    code: 'bs_tin',
    countryCode: 'BS',
    countryName: 'Bahamas',
    taxName: 'Bahamas Tax Identification Number',
    taxNumberPlaceholder: '123.456.789',
    percentage: undefined,
  },
  {
    code: 'bh_vat',
    countryCode: 'BH',
    countryName: 'Bahrain',
    taxName: 'Bahraini VAT Number',
    taxNumberPlaceholder: '123456789012345',
    percentage: undefined,
  },
  {
    code: 'bb_tin',
    countryCode: 'BB',
    countryName: 'Barbados',
    taxName: 'Barbados Tax Identification Number',
    taxNumberPlaceholder: '1123456789012',
    percentage: undefined,
  },
  {
    code: 'by_tin',
    countryCode: 'BY',
    countryName: 'Belarus',
    taxName: 'Belarus TIN Number',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'BE',
    countryName: 'Belgium',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'BE0123456789',
    percentage: 21,
  },
  {
    code: 'bo_tin',
    countryCode: 'BO',
    countryName: 'Bolivia',
    taxName: 'Bolivian tax ID',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'ba_tin',
    countryCode: 'BA',
    countryName: 'Bosnia & Herzegovina',
    taxName: 'Bosnia and Herzegovina Tax Identification Number',
    taxNumberPlaceholder: '123456789012',
    percentage: undefined,
  },
  {
    code: 'br_cnpj',
    countryCode: 'BR',
    countryName: 'Brazil',
    taxName: 'Brazilian CNPJ number',
    taxNumberPlaceholder: '01.234.456/5432-10',
    percentage: undefined,
  },
  {
    code: 'br_cpf',
    countryCode: 'BR',
    countryName: 'Brazil',
    taxName: 'Brazilian CPF number',
    taxNumberPlaceholder: '123.456.789-87',
    percentage: undefined,
  },
  {
    code: 'bg_uic',
    countryCode: 'BG',
    countryName: 'Bulgaria',
    taxName: 'Bulgaria Unified Identification Code',
    taxNumberPlaceholder: '123456789',
    percentage: 20,
  },
  {
    code: 'eu_vat',
    countryCode: 'BG',
    countryName: 'Bulgaria',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'BG0123456789',
    percentage: 20,
  },
  {
    code: 'kh_tin',
    countryCode: 'KH',
    countryName: 'Cambodia',
    taxName: 'Cambodia Tax Identification Number',
    taxNumberPlaceholder: '1001-123456789',
    percentage: undefined,
  },
  {
    code: 'ca_bn',
    countryCode: 'CA',
    countryName: 'Canada',
    taxName: 'Canadian BN',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'ca_gst_hst',
    countryCode: 'CA',
    countryName: 'Canada',
    taxName: 'Canadian GST/HST number',
    taxNumberPlaceholder: '123456789RT0002',
    percentage: undefined,
  },
  {
    code: 'ca_pst_bc',
    countryCode: 'CA',
    countryName: 'Canada',
    taxName: 'Canadian PST number (British Columbia)',
    taxNumberPlaceholder: 'PST-1234-5678',
    percentage: undefined,
  },
  {
    code: 'ca_pst_mb',
    countryCode: 'CA',
    countryName: 'Canada',
    taxName: 'Canadian PST number (Manitoba)',
    taxNumberPlaceholder: '123456-7',
    percentage: undefined,
  },
  {
    code: 'ca_pst_mb',
    countryCode: 'CA',
    countryName: 'Canada',
    taxName: 'Canadian PST number (Saskatchewan)',
    taxNumberPlaceholder: '1234567',
    percentage: undefined,
  },
  {
    code: 'ca_pst_mb',
    countryCode: 'CA',
    countryName: 'Canada',
    taxName: 'Canadian QST number (Québec)',
    taxNumberPlaceholder: '123456-7',
    percentage: undefined,
  },
  {
    code: 'cl_tin',
    countryCode: 'CL',
    countryName: 'Chile',
    taxName: 'Chilean TIN',
    taxNumberPlaceholder: '12.345.678-K',
    percentage: undefined,
  },
  {
    code: 'cn_tin',
    countryCode: 'CN',
    countryName: 'China',
    taxName: 'Chinese tax ID',
    taxNumberPlaceholder: '123456789012345678',
    percentage: undefined,
  },
  {
    code: 'co_nit',
    countryCode: 'CO',
    countryName: 'Colombia',
    taxName: 'Colombian NIT number',
    taxNumberPlaceholder: '123.456.789-0',
    percentage: undefined,
  },
  {
    code: 'cd_nif',
    countryCode: 'CD',
    countryName: 'Congo - Kinshasa',
    taxName: 'Congo (DR) Tax Identification Number (Número de Identificação Fiscal)',
    taxNumberPlaceholder: 'A0123456M',
    percentage: undefined,
  },
  {
    code: 'cr_tin',
    countryCode: 'CR',
    countryName: 'Costa Rica',
    taxName: 'Costa Rican tax ID',
    taxNumberPlaceholder: '1-234-567890',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'HR',
    countryName: 'Croatia',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'HR12345678912',
    percentage: 25,
  },
  {
    code: 'hr_oib',
    countryCode: 'HR',
    countryName: 'Croatia',
    taxName: 'Croatian Personal Identification Number',
    taxNumberPlaceholder: '12345678901',
    percentage: 25,
  },
  {
    code: 'eu_vat',
    countryCode: 'CY',
    countryName: 'Cyprus',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'CY12345678Z',
    percentage: 19,
  },
  {
    code: 'eu_vat',
    countryCode: 'CZ',
    countryName: 'Czechia',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'CZ1234567890',
    percentage: 21,
  },
  {
    code: 'eu_vat',
    countryCode: 'DK',
    countryName: 'Denmark',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'DK12345678',
    percentage: 25,
  },
  {
    code: 'do_rcn',
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    taxName: 'Dominican RCN number',
    taxNumberPlaceholder: '123-4567890-1',
    percentage: undefined,
  },
  {
    code: 'ec_ruc',
    countryCode: 'EC',
    countryName: 'Ecuador',
    taxName: 'Ecuadorian RUC number',
    taxNumberPlaceholder: '1234567890001',
    percentage: undefined,
  },
  {
    code: 'eg_tin',
    countryCode: 'EG',
    countryName: 'Egypt',
    taxName: 'Egyptian Tax Identification Number',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'sv_nit',
    countryCode: 'SV',
    countryName: 'El Salvador',
    taxName: 'El Salvadorian NIT number',
    taxNumberPlaceholder: '1234-567890-123-4',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'EE',
    countryName: 'Estonia',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'EE123456789',
    percentage: 22,
  },
  {
    code: 'eu_vat',
    countryCode: 'FI',
    countryName: 'Finland',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'FI12345678',
    percentage: 25.5,
  },
  {
    code: 'eu_vat',
    countryCode: 'FR',
    countryName: 'France',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'FRAB123456789',
    percentage: 20,
  },
  {
    code: 'eu_vat',
    countryCode: 'GP',
    countryName: 'Guadeloupe',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'FRAB123456789',
    percentage: 8.5,
  },
  {
    code: 'eu_vat',
    countryCode: 'MQ',
    countryName: 'Martinique',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'FRAB123456789',
    percentage: 8.5,
  },
  {
    code: 'eu_vat',
    countryCode: 'RE',
    countryName: 'Réunion',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'FRAB123456789',
    percentage: 8.5,
  },
  {
    code: 'ge_vat',
    countryCode: 'GE',
    countryName: 'Georgia',
    taxName: 'Georgian VAT',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'de_stn',
    countryCode: 'DE',
    countryName: 'Germany',
    taxName: 'German Tax Number (Steuernummer)',
    taxNumberPlaceholder: '1234567890',
    percentage: 19,
  },
  {
    code: 'eu_vat',
    countryCode: 'DE',
    countryName: 'Germany',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'DE123456789',
    percentage: 19,
  },
  {
    code: 'eu_vat',
    countryCode: 'GR',
    countryName: 'Greece',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'EL123456789',
    percentage: 24,
  },
  {
    code: 'gn_nif',
    countryCode: 'GN',
    countryName: 'Guinea',
    taxName: 'Guinea Tax Identification Number (Número de Identificação Fiscal)',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'hk_br',
    countryCode: 'HK',
    countryName: 'Hong Kong SAR China',
    taxName: 'Hong Kong BR number',
    taxNumberPlaceholder: '12345678',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'HU',
    countryName: 'Hungary',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'HU12345678',
    percentage: 27,
  },
  {
    code: 'hu_tin',
    countryCode: 'HU',
    countryName: 'Hungary',
    taxName: 'Hungary tax number (adószám)',
    taxNumberPlaceholder: '12345678-1-23',
    percentage: 27,
  },
  {
    code: 'is_vat',
    countryCode: 'IS',
    countryName: 'Iceland',
    taxName: 'Icelandic VAT',
    taxNumberPlaceholder: '123456',
    percentage: undefined,
  },
  {
    code: 'in_gst',
    countryCode: 'IN',
    countryName: 'India',
    taxName: 'Indian GST number',
    taxNumberPlaceholder: '12ABCDE3456FGZH',
    percentage: undefined,
  },
  {
    code: 'id_npwp',
    countryCode: 'ID',
    countryName: 'Indonesia',
    taxName: 'Indonesian NPWP number',
    taxNumberPlaceholder: '012.345.678.9-012.345',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'IE',
    countryName: 'Ireland',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'IE1234567AB',
    percentage: 23,
  },
  {
    code: 'il_vat',
    countryCode: 'IL',
    countryName: 'Israel',
    taxName: 'Israel VAT',
    taxNumberPlaceholder: '000012345',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'IT',
    countryName: 'Italy',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'IT12345678912',
    percentage: 22,
  },
  {
    code: 'jp_cn',
    countryCode: 'JP',
    countryName: 'Japan',
    taxName: 'Japanese Corporate Number (*Hōjin Bangō*)',
    taxNumberPlaceholder: '1234567891234',
    percentage: undefined,
  },
  {
    code: 'jp_rn',
    countryCode: 'JP',
    countryName: 'Japan',
    taxName: 'Japanese Registered Foreign Businesses\' Registration Number (\'Tōroku Kokugai Jigyōsha no Tōroku Bangō*)',
    taxNumberPlaceholder: '12345',
    percentage: undefined,
  },
  {
    code: 'jp_trn',
    countryCode: 'JP',
    countryName: 'Japan',
    taxName: 'Japanese Tax Registration Number (*Tōroku Bangō*)',
    taxNumberPlaceholder: 'T1234567891234',
    percentage: undefined,
  },
  {
    code: 'kz_bin',
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    taxName: 'Kazakhstani Business Identification Number',
    taxNumberPlaceholder: '123456789012',
    percentage: undefined,
  },
  {
    code: 'ke_pin',
    countryCode: 'KE',
    countryName: 'Kenya',
    taxName: 'Kenya Revenue Authority Personal Identification Number',
    taxNumberPlaceholder: 'P000111111A',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'LV',
    countryName: 'Latvia',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'LV12345678912',
    percentage: 21,
  },
  {
    code: 'li_uid',
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    taxName: 'Liechtensteinian UID number',
    taxNumberPlaceholder: 'CHE123456789',
    percentage: undefined,
  },
  {
    code: 'li_vat',
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    taxName: 'Liechtenstein VAT number',
    taxNumberPlaceholder: '12345',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'LT',
    countryName: 'Lithuania',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'LT123456789123',
    percentage: 21,
  },
  {
    code: 'eu_vat',
    countryCode: 'LU',
    countryName: 'Luxembourg',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'LU12345678',
    percentage: 17,
  },
  {
    code: 'my_frp',
    countryCode: 'MY',
    countryName: 'Malaysia',
    taxName: 'Malaysian FRP number',
    taxNumberPlaceholder: '12345678',
    percentage: undefined,
  },
  {
    code: 'my_itn',
    countryCode: 'MY',
    countryName: 'Malaysia',
    taxName: 'Malaysian ITN',
    taxNumberPlaceholder: 'C 1234567890',
    percentage: undefined,
  },
  {
    code: 'my_sst',
    countryCode: 'MY',
    countryName: 'Malaysia',
    taxName: 'Malaysian SST number',
    taxNumberPlaceholder: 'A12-3456-78912345',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'MT',
    countryName: 'Malta',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'MT12345678',
    percentage: 18,
  },
  {
    code: 'mr_nif',
    countryCode: 'MR',
    countryName: 'Mauritania',
    taxName: 'Mauritania Tax Identification Number (Número de Identificação Fiscal)',
    taxNumberPlaceholder: '12345678',
    percentage: undefined,
  },
  {
    code: 'mx_rfc',
    countryCode: 'MX',
    countryName: 'Mexico',
    taxName: 'Mexican RFC number',
    taxNumberPlaceholder: 'ABC010203AB9',
    percentage: undefined,
  },
  {
    code: 'md_vat',
    countryCode: 'MD',
    countryName: 'Moldova',
    taxName: 'Moldova VAT Number',
    taxNumberPlaceholder: '1234567',
    percentage: undefined,
  },
  {
    code: 'me_pib',
    countryCode: 'ME',
    countryName: 'Montenegro',
    taxName: 'Montenegro PIB Number',
    taxNumberPlaceholder: '12345678',
    percentage: undefined,
  },
  {
    code: 'ma_vat',
    countryCode: 'MA',
    countryName: 'Morocco',
    taxName: 'Morocco VAT Number',
    taxNumberPlaceholder: '12345678',
    percentage: undefined,
  },
  {
    code: 'np_pan',
    countryCode: 'NP',
    countryName: 'Nepal',
    taxName: 'Nepal PAN Number',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'NL',
    countryName: 'Netherlands',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'NL123456789B12',
    percentage: 21,
  },
  {
    code: 'nz_gst',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    taxName: 'New Zealand GST number',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'ng_tin',
    countryCode: 'NG',
    countryName: 'Nigeria',
    taxName: 'Nigerian Tax Identification Number',
    taxNumberPlaceholder: '12345678-0001',
    percentage: undefined,
  },
  {
    code: 'mk_vat',
    countryCode: 'MK',
    countryName: 'North Macedonia',
    taxName: 'North Macedonia VAT Number',
    taxNumberPlaceholder: 'MK1234567890123',
    percentage: undefined,
  },
  {
    code: 'no_vat',
    countryCode: 'NO',
    countryName: 'Norway',
    taxName: 'Norwegian VAT number',
    taxNumberPlaceholder: '123456789MVA',
    percentage: undefined,
  },
  {
    code: 'no_voec',
    countryCode: 'NO',
    countryName: 'Norway',
    taxName: 'Norwegian VAT on e-commerce number',
    taxNumberPlaceholder: '1234567',
    percentage: undefined,
  },
  {
    code: 'om_vat',
    countryCode: 'OM',
    countryName: 'Oman',
    taxName: 'Omani VAT Number',
    taxNumberPlaceholder: 'OM1234567890',
    percentage: undefined,
  },
  {
    code: 'pe_ruc',
    countryCode: 'PE',
    countryName: 'Peru',
    taxName: 'Peruvian RUC number',
    taxNumberPlaceholder: '12345678901',
    percentage: undefined,
  },
  {
    code: 'ph_tin',
    countryCode: 'PH',
    countryName: 'Philippines',
    taxName: 'Philippines Tax Identification Number',
    taxNumberPlaceholder: '123456789012',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'PL',
    countryName: 'Poland',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'PL1234567890',
    percentage: 23,
  },
  {
    code: 'eu_vat',
    countryCode: 'PT',
    countryName: 'Portugal',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'PT123456789',
    percentage: 23,
  },
  {
    code: 'eu_vat',
    countryCode: 'RO',
    countryName: 'Romania',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'RO1234567891',
    percentage: 19,
  },
  {
    code: 'ro_tin',
    countryCode: 'RO',
    countryName: 'Romania',
    taxName: 'Romanian tax ID number',
    taxNumberPlaceholder: '1234567890123',
    percentage: 19,
  },
  {
    code: 'ru_inn',
    countryCode: 'RU',
    countryName: 'Russia',
    taxName: 'Russian INN',
    taxNumberPlaceholder: '1234567891',
    percentage: undefined,
  },
  {
    code: 'ru_kpp',
    countryCode: 'RU',
    countryName: 'Russia',
    taxName: 'Russian KPP',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'sa_vat',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    taxName: 'Saudi Arabia VAT',
    taxNumberPlaceholder: '123456789012345',
    percentage: undefined,
  },
  {
    code: 'sn_ninea',
    countryCode: 'SN',
    countryName: 'Senegal',
    taxName: 'Senegal NINEA Number',
    taxNumberPlaceholder: '12345672A2',
    percentage: undefined,
  },
  {
    code: 'rs_pib',
    countryCode: 'RS',
    countryName: 'Serbia',
    taxName: 'Serbian PIB number',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'sg_gst',
    countryCode: 'SG',
    countryName: 'Singapore',
    taxName: 'Singaporean GST',
    taxNumberPlaceholder: 'M12345678X',
    percentage: undefined,
  },
  {
    code: 'sg_uen',
    countryCode: 'SG',
    countryName: 'Singapore',
    taxName: 'Singaporean UEN',
    taxNumberPlaceholder: '123456789F',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'SK',
    countryName: 'Slovakia',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'SK1234567891',
    percentage: 23,
  },
  {
    code: 'eu_vat',
    countryCode: 'SI',
    countryName: 'Slovenia',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'SI12345678',
    percentage: 22,
  },
  {
    code: 'si_tin',
    countryCode: 'SI',
    countryName: 'Slovenia',
    taxName: 'Slovenia tax number (davčna številka)',
    taxNumberPlaceholder: '12345678',
    percentage: 22,
  },
  {
    code: 'za_vat',
    countryCode: 'ZA',
    countryName: 'South Africa',
    taxName: 'South African VAT number',
    taxNumberPlaceholder: '4123456789',
    percentage: undefined,
  },
  {
    code: 'kr_brn',
    countryCode: 'KR',
    countryName: 'South Korea',
    taxName: 'Korean BRN',
    taxNumberPlaceholder: '123-45-67890',
    percentage: undefined,
  },
  {
    code: 'es_cif',
    countryCode: 'ES',
    countryName: 'Spain',
    taxName: 'Spanish NIF number (previously Spanish CIF number)',
    taxNumberPlaceholder: 'A12345678',
    percentage: 21,
  },
  {
    code: 'eu_vat',
    countryCode: 'ES',
    countryName: 'Spain',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'ESA1234567Z',
    percentage: 21,
  },
  {
    code: 'sr_fin',
    countryCode: 'SR',
    countryName: 'Suriname',
    taxName: 'Suriname FIN Number',
    taxNumberPlaceholder: '1234567890',
    percentage: undefined,
  },
  {
    code: 'eu_vat',
    countryCode: 'SE',
    countryName: 'Sweden',
    taxName: 'European VAT number',
    taxNumberPlaceholder: 'SE123456789123',
    percentage: 25,
  },
  {
    code: 'ch_uid',
    countryCode: 'CH',
    countryName: 'Switzerland',
    taxName: 'Switzerland UID number',
    taxNumberPlaceholder: 'CHE-123.456.789 HR',
    percentage: undefined,
  },
  {
    code: 'ch_vat',
    countryCode: 'CH',
    countryName: 'Switzerland',
    taxName: 'Switzerland VAT number',
    taxNumberPlaceholder: 'CHE-123.456.789 MWST',
    percentage: undefined,
  },
  {
    code: 'tw_vat',
    countryCode: 'TW',
    countryName: 'Taiwan',
    taxName: 'Taiwanese VAT',
    taxNumberPlaceholder: '12345678',
    percentage: undefined,
  },
  {
    code: 'tj_tin',
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    taxName: 'Tajikistan Tax Identification Number',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'tz_vat',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    taxName: 'Tanzania VAT Number',
    taxNumberPlaceholder: '12345678A',
    percentage: undefined,
  },
  {
    code: 'th_vat',
    countryCode: 'TH',
    countryName: 'Thailand',
    taxName: 'Thai VAT',
    taxNumberPlaceholder: '1234567891234',
    percentage: undefined,
  },
  {
    code: 'tr_tin',
    countryCode: 'TR',
    countryName: 'Türkiye',
    taxName: 'Turkish Tax Identification Number',
    taxNumberPlaceholder: '0123456789',
    percentage: undefined,
  },
  {
    code: 'ug_tin',
    countryCode: 'UG',
    countryName: 'Uganda',
    taxName: 'Uganda Tax Identification Number',
    taxNumberPlaceholder: '1014751879',
    percentage: undefined,
  },
  {
    code: 'ua_vat',
    countryCode: 'UA',
    countryName: 'Ukraine',
    taxName: 'Ukrainian VAT',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'ae_trn',
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    taxName: 'United Arab Emirates TRN',
    taxNumberPlaceholder: '123456789012345',
    percentage: undefined,
  },
  // {
  //   code: 'eu_vat',
  //   countryCode: 'GB',
  //   countryName: 'United Kingdom',
  //   taxName: 'Northern Ireland VAT number',
  //   taxNumberPlaceholder: 'XI123456789',
  //   percentage: undefined,
  // },
  {
    code: 'gb_vat',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    taxName: 'United Kingdom VAT number',
    taxNumberPlaceholder: 'GB123456789',
    percentage: undefined,
  },
  {
    code: 'us_ein',
    countryCode: 'US',
    countryName: 'United States',
    taxName: 'United States EIN',
    taxNumberPlaceholder: '12-3456789',
    percentage: undefined,
  },
  {
    code: 'uy_ruc',
    countryCode: 'UY',
    countryName: 'Uruguay',
    taxName: 'Uruguayan RUC number',
    taxNumberPlaceholder: '123456789012',
    percentage: undefined,
  },
  {
    code: 'uz_tin',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    taxName: 'Uzbekistan TIN Number',
    taxNumberPlaceholder: '123456789',
    percentage: undefined,
  },
  {
    code: 'uz_vat',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    taxName: 'Uzbekistan VAT Number',
    taxNumberPlaceholder: '123456789012',
    percentage: undefined,
  },
  {
    code: 've_rif',
    countryCode: 'VE',
    countryName: 'Venezuela',
    taxName: 'Venezuelan RIF number',
    taxNumberPlaceholder: 'A-12345678-9',
    percentage: undefined,
  },
  {
    code: 'vn_tin',
    countryCode: 'VN',
    countryName: 'Vietnam',
    taxName: 'Vietnamese tax ID number',
    taxNumberPlaceholder: '1234567890',
    percentage: undefined,
  },
  {
    code: 'zm_tin',
    countryCode: 'ZM',
    countryName: 'Zambia',
    taxName: 'Zambia Tax Identification Number',
    taxNumberPlaceholder: '1004751879',
    percentage: undefined,
  },
  {
    code: 'zw_tin',
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    taxName: 'Zimbabwe Tax Identification Number',
    taxNumberPlaceholder: '1234567890',
    percentage: undefined,
  },
  {
    code: 'eu_oss_vat',
    countryName: 'EU',
    taxName: 'European One Stop Shop VAT number for non-Union scheme',
    taxNumberPlaceholder: 'EU123456789',
    percentage: undefined,
  },
];

export default TAXES;
