import INVITATIONS_TABLE_HEADERS from './INVITATIONS_TABLE_HEADERS.jsx';
import INVITATIONS_TABS_FILTERS from './INVITATIONS_TABS_FILTERS.jsx';
import INVITATIONS_TABLE_CONFIG from './INVITATIONS_TABLE_CONFIG.jsx';

export {
  INVITATIONS_TABLE_HEADERS,
  INVITATIONS_TABS_FILTERS,
  INVITATIONS_TABLE_CONFIG,
};
