import {
  fromNow,
} from '@/utils';

const INVITATIONS_TABLE_HEADERS = {
  pending: [
    {
      id: 'email',
      orderByParam: 'email',
      disablePadding: false,
      label: 'Email',
      type: 'text',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 2,
      mobileColSpan: 2,
      formatValue: ({ value }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'status',
      orderByParam: 'status',
      disablePadding: false,
      label: 'Status',
      hasTooltip: false,
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      type: 'chip',
      formatValue: () => ({
        name: 'Pending',
        color: 'primary.main',
      }),
    },
    {
      id: 'createdAt',
      orderByParam: 'createdAt',
      disablePadding: false,
      label: 'Sent',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: 'invitedByEmail',
      orderByParam: 'invitedByEmail',
      disablePadding: false,
      label: 'Sent by',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
      }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'expiresAt',
      orderByParam: 'expiresAt',
      disablePadding: false,
      label: 'Expires',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => (
        value ? fromNow(value, dateFnsLocale) : 'Never'
      ),
    },
    {
      id: '',
      orderByParam: '',
      disablePadding: false,
      label: '',
      type: '',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: true,
      colSpan: 1,
    },
  ],
  accepted: [
    {
      id: 'email',
      orderByParam: 'email',
      disablePadding: false,
      label: 'Email',
      type: 'text',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 2,
      mobileColSpan: 2,
      formatValue: ({ value }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'status',
      orderByParam: 'status',
      disablePadding: false,
      label: 'Status',
      hasTooltip: false,
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      type: 'chip',
      formatValue: () => ({
        name: 'Accepted',
        color: 'success.main',
      }),
    },
    {
      id: 'createdAt',
      orderByParam: 'createdAt',
      disablePadding: false,
      label: 'Sent',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: 'invitedByEmail',
      orderByParam: 'invitedByEmail',
      disablePadding: false,
      label: 'Sent by',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
      }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'answeredAt',
      orderByParam: 'answeredAt',
      disablePadding: false,
      label: 'Accepted',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: '',
      orderByParam: '',
      disablePadding: false,
      label: '',
      type: '',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: true,
      colSpan: 1,
    },
  ],
  expired: [
    {
      id: 'email',
      orderByParam: 'email',
      disablePadding: false,
      label: 'Email',
      type: 'text',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 2,
      mobileColSpan: 2,
      formatValue: ({ value }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'status',
      orderByParam: 'status',
      disablePadding: false,
      label: 'Status',
      hasTooltip: false,
      type: 'chip',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: () => ({
        name: 'Expired',
        color: 'warning.main',
      }),
    },
    {
      id: 'createdAt',
      orderByParam: 'createdAt',
      disablePadding: false,
      label: 'Sent',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: 'expiresAt',
      orderByParam: 'expiresAt',
      disablePadding: false,
      label: 'Expired',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: 'invitedByEmail',
      orderByParam: 'invitedByEmail',
      disablePadding: false,
      label: 'Sent by',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
      }) => (
        value || 'N/A'
      ),
    },
    {
      id: '',
      orderByParam: '',
      disablePadding: false,
      label: '',
      type: '',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: true,
      colSpan: 1,
    },
  ],
  declined: [
    {
      id: 'email',
      orderByParam: 'email',
      disablePadding: false,
      label: 'Email',
      type: 'text',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 2,
      mobileColSpan: 2,
      formatValue: ({ value }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'status',
      orderByParam: 'status',
      disablePadding: false,
      label: 'Status',
      hasTooltip: false,
      type: 'chip',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: () => ({
        name: 'Declined',
        color: 'error.light',
      }),
    },
    {
      id: 'createdAt',
      orderByParam: 'createdAt',
      disablePadding: false,
      label: 'Sent',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: 'invitedByEmail',
      orderByParam: 'invitedByEmail',
      disablePadding: false,
      label: 'Sent by',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
      }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'answeredAt',
      orderByParam: 'answeredAt',
      disablePadding: false,
      label: 'Declined',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: '',
      orderByParam: '',
      disablePadding: false,
      label: '',
      type: '',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: true,
      colSpan: 1,
    },
  ],
  cancelled: [
    {
      id: 'email',
      orderByParam: 'email',
      disablePadding: false,
      label: 'Email',
      type: 'text',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 2,
      mobileColSpan: 2,
      formatValue: ({ value }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'status',
      orderByParam: 'status',
      disablePadding: false,
      label: 'Status',
      hasTooltip: false,
      type: 'chip',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: () => ({
        name: 'Cancelled',
        color: 'error.dark',
      }),
    },
    {
      id: 'createdAt',
      orderByParam: 'createdAt',
      disablePadding: false,
      label: 'Sent',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: 'invitedByEmail',
      orderByParam: 'invitedByEmail',
      disablePadding: false,
      label: 'Sent by',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
      }) => (
        value || 'N/A'
      ),
    },
    {
      id: 'cancelledAt',
      orderByParam: 'cancelledAt',
      disablePadding: false,
      label: 'Cancelled',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
        dateFnsLocale,
      }) => fromNow(value, dateFnsLocale),
    },
    {
      id: 'cancelledByEmail',
      orderByParam: 'cancelledByEmail',
      disablePadding: false,
      label: 'Cancelled by',
      type: 'text',
      hiddenOnMobile: true,
      hiddenOnTablet: false,
      disallowSorting: false,
      colSpan: 1,
      formatValue: ({
        value,
      }) => (
        value || 'N/A'
      ),
    },
    {
      id: '',
      orderByParam: '',
      disablePadding: false,
      label: '',
      type: '',
      hiddenOnMobile: false,
      hiddenOnTablet: false,
      disallowSorting: true,
      colSpan: 1,
    },
  ],
};

export default INVITATIONS_TABLE_HEADERS; 